import { Grid } from "../../lib/grid.ts";
import { Location } from "../../lib/location.ts";
import { ObjectSet } from "../../lib/object_set.ts";

/** --- Day 7: Laboratories ---
 *
 * You thank the cephalopods for the help and exit the trash compactor,
 * finding yourself in the familiar halls of a North Pole research wing.
 *
 * Based on the large sign that says "teleporter hub", they seem to be
 * researching teleportation; you can't help but try it for yourself and step
 * onto the large yellow teleporter pad.
 *
 * Suddenly, you find yourself in an unfamiliar room! The room has no doors;
 * the only way out is the teleporter. Unfortunately, the teleporter seems to
 * be leaking magic smoke.
 *
 * Since this is a teleporter lab, there are lots of spare parts, manuals, and
 * diagnostic equipment lying around. After connecting one of the diagnostic
 * tools, it helpfully displays error code 0H-N0, which apparently means that
 * there's an issue with one of the tachyon manifolds.
 *
 * You quickly locate a diagram of the tachyon manifold (your puzzle input).
 * A tachyon beam enters the manifold at the location marked S; tachyon beams
 * always move downward. Tachyon beams pass freely through empty space (.).
 * However, if a tachyon beam encounters a splitter (^), the beam is stopped;
 * instead, a new tachyon beam continues from the immediate left and from the
 * immediate right of the splitter.
 *
 * For example:
 *
 * .......S.......
 * ...............
 * .......^.......
 * ...............
 * ......^.^......
 * ...............
 * .....^.^.^.....
 * ...............
 * ....^.^...^....
 * ...............
 * ...^.^...^.^...
 * ...............
 * ..^...^.....^..
 * ...............
 * .^.^.^.^.^...^.
 * ...............
 *
 * In this example, the incoming tachyon beam (|) extends downward from S
 * until it reaches the first splitter:
 *
 * .......S.......
 * .......|.......
 * .......^.......
 * ...............
 * ......^.^......
 * ...............
 * .....^.^.^.....
 * ...............
 * ....^.^...^....
 * ...............
 * ...^.^...^.^...
 * ...............
 * ..^...^.....^..
 * ...............
 * .^.^.^.^.^...^.
 * ...............
 *
 * At that point, the original beam stops, and two new beams are emitted
 * from the splitter:
 *
 * .......S.......
 * .......|.......
 * ......|^|......
 * ...............
 * ......^.^......
 * ...............
 * .....^.^.^.....
 * ...............
 * ....^.^...^....
 * ...............
 * ...^.^...^.^...
 * ...............
 * ..^...^.....^..
 * ...............
 * .^.^.^.^.^...^.
 * ...............
 *
 * Those beams continue downward until they reach more splitters:
 *
 * .......S.......
 * .......|.......
 * ......|^|......
 * ......|.|......
 * ......^.^......
 * ...............
 * .....^.^.^.....
 * ...............
 * ....^.^...^....
 * ...............
 * ...^.^...^.^...
 * ...............
 * ..^...^.....^..
 * ...............
 * .^.^.^.^.^...^.
 * ...............
 *
 * At this point, the two splitters create a total of only three tachyon
 * beams, since they are both dumping tachyons into the same place between them:
 *
 * .......S.......
 * .......|.......
 * ......|^|......
 * ......|.|......
 * .....|^|^|.....
 * ...............
 * .....^.^.^.....
 * ...............
 * ....^.^...^....
 * ...............
 * ...^.^...^.^...
 * ...............
 * ..^...^.....^..
 * ...............
 * .^.^.^.^.^...^.
 * ...............
 *
 * This process continues until all of the tachyon beams reach a splitter or
 * exit the manifold:
 *
 * .......S.......
 * .......|.......
 * ......|^|......
 * ......|.|......
 * .....|^|^|.....
 * .....|.|.|.....
 * ....|^|^|^|....
 * ....|.|.|.|....
 * ...|^|^|||^|...
 * ...|.|.|||.|...
 * ..|^|^|||^|^|..
 * ..|.|.|||.|.|..
 * .|^|||^||.||^|.
 * .|.|||.||.||.|.
 * |^|^|^|^|^|||^|
 * |.|.|.|.|.|||.|
 *
 * To repair the teleporter, you first need to understand the beam-splitting
 * properties of the tachyon manifold. In this example, a tachyon beam is
 * split a total of 21 times.
 *
 * Analyze your manifold diagram. How many times will the beam be split?
 */

export function part_1(input: string): string {
  const grid = Grid.gridFromString(input);
  const sLoc = grid.find("S");

  let beams = new ObjectSet<Location>((o) => o.toString());
  beams.set(sLoc!);

  let splits = 0;
  for (let rowIdx = 1; rowIdx < grid.numRows(); rowIdx++) {
    ({ beams, splits } = generateNextLine(beams, grid, splits));

    // for (const beam of beams) grid.setAt(beam, "|");
    // // ===> beams.values().forEach((beam) => grid.setAt(beam, "|"));
    // console.log(grid.representation());
    // console.log(beams.size);
    // console.log(splits);
  }

  return `${splits}`;
}

export function part_2(_input: string): string {
  return `PENDING`;
}

function generateNextLine(
  beams: ObjectSet<Location>,
  grid: Grid<string>,
  splits: number,
): { beams: ObjectSet<Location>; splits: number } {
  const newBeams = new ObjectSet<Location>();
  for (const beam of beams) {
    const newBeam = beam.addXY(0, 1);
    if (grid.at(newBeam) === "^") {
      newBeams.set(newBeam.addXY(-1, 0));
      newBeams.set(newBeam.addXY(1, 0));
      splits += 1;
    } else {
      newBeams.set(newBeam);
    }
  }

  return { beams: newBeams, splits: splits };
}
