plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  CountRepeatedAttributes: false
Metrics/BlockLength:
  CountAsOne: [ "array", "hash", "heredoc", "method_call" ]
Metrics/MethodLength:
  CountAsOne: [ "array", "hash", "heredoc", "method_call" ]
Metrics/ModuleLength:
  CountAsOne: [ "array", "hash", "heredoc", "method_call" ]

Style/Documentation:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInBlockArgs:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
