name: CMake (2022)

on:
  push:
    branches: [ "main" ]
    paths:
      - 2022-cpp/**
  pull_request:
    branches: [ "main" ]
    paths:
      - 2022-cpp/**
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}/2022-cpp
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/2022-cpp
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/2022-cpp/build
      run: ctest -C ${{env.BUILD_TYPE}}

